# Generated by Django 3.2.5 on 2021-07-05 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
                ('category_type', models.CharField(choices=[('S', 'Saídas'), ('E', 'Entradas')], default='S', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContasReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('value', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
                ('payment_method', models.CharField(choices=[('CD', 'Débito'), ('CC', 'Crédito'), ('T', 'Transferência'), ('P', 'Depósito'), ('C', 'Cheque'), ('D', 'Dinheiro'), ('B', 'Boleto')], default='D', max_length=20)),
                ('status', models.CharField(choices=[('T', 'Recebido'), ('F', 'A receber')], default='F', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo_caixa.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
                ('payment_method', models.CharField(choices=[('CD', 'Débito'), ('CC', 'Crédito'), ('T', 'Transferência'), ('P', 'Depósito'), ('C', 'Cheque'), ('D', 'Dinheiro'), ('B', 'Boleto')], default='D', max_length=20)),
                ('status', models.CharField(choices=[('T', 'Pago'), ('F', 'A pagar')], default='F', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo_caixa.categorias')),
            ],
        ),
    ]
